# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PygdalsarViewer
                                 A QGIS plugin
 Viewer tools for raster time series with multiple geometry aquisitions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-30
        copyright            : (C) 2026 by Léo Letelier, Hugo Watine, Simon Daout
        email                : leo.letellier@univ-lorraine.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PygdalsarViewer class from file PygdalsarViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Pygdalsar_Viewer import PygdalsarViewer
    return PygdalsarViewer(iface)
