# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PygdalsarViewer
                                 A QGIS plugin
 Viewer tools for raster time series with multiple geometry aquisitions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Léo Letelier, Hugo Watine, Simon Daout
        email                : leo.letellier@univ-lorraine.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os.path

from qgis.PyQt.QtCore import QCoreApplication, QSettings, Qt, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
from .ui.pygdalsar_viewer_cube import PygdalsarViewerCube
from .ui.pygdalsar_viewer_section import PygdalsarViewerSection
from .ui.pygdalsar_viewer_ts import PygdalsarViewerTS


class PygdalsarViewer:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "PygdalsarViewer_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&PyGdalSAR Viewer")
        self.toolbar = self.iface.addToolBar("PygdalsarViewer")
        self.toolbar.setObjectName("PygdalsarViewer")

        self.pluginIsActive = False
        self.viewerCube = None
        self.viewerTS = None
        self.viewerSection = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        return QCoreApplication.translate("PygdalsarViewer", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
        checkable=False,
    ):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        action.setCheckable(checkable)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI"""

        icon_path = ":/plugins/Pygdalsar_Viewer/icon.png"
        self.action_viewer = self.add_action(
            icon_path,
            text=self.tr("PyGdalSAR Viewer"),
            callback=self.run_cube,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        icon_path = ":/plugins/Pygdalsar_Viewer/icon.png"
        self.action_ts = self.add_action(
            icon_path,
            text=self.tr("PyGdalSAR Time Series"),
            callback=self.run_ts,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        icon_path = ":/plugins/Pygdalsar_Viewer/icon.png"
        self.action_section = self.add_action(
            icon_path,
            text=self.tr("PyGdalSAR Section"),
            callback=self.run_section,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

    def onClosePlugin(self, viewer):
        """Cleanup necessary items when a specific viewer is closed"""
        # Disconnect the signal for the closed viewer
        try:
            viewer.closingPlugin.disconnect()
        except TypeError:
            pass  # Signal was not connected, ignore

        # Reset the viewer reference and action state
        if viewer == self.viewerCube:
            self.viewerCube = None
            self.action_viewer.setChecked(False)
        elif viewer == self.viewerTS:
            self.viewerTS = None
            self.action_ts.setChecked(False)
        elif viewer == self.viewerSection:
            self.viewerSection = None
            self.action_section.setChecked(False)

        # Update pluginIsActive if all viewers are closed
        if (
            self.viewerCube is None
            and self.viewerTS is None
            and self.viewerSection is None
        ):
            self.pluginIsActive = False

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI"""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr("&PyGdalSAR Viewer"), action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar

    def run_cube(self, checked: bool):
        if checked:
            if self.viewerCube is None:
                self.viewerCube = PygdalsarViewerCube()
                # Pass the viewer instance to onClosePlugin
                self.viewerCube.closingPlugin.connect(
                    lambda: self.onClosePlugin(self.viewerCube)
                )
            self.iface.addDockWidget(Qt.TopDockWidgetArea, self.viewerCube)
            self.viewerCube.show()
        else:
            if self.viewerCube is not None:
                self.viewerCube.close()

    def run_section(self, checked: bool):
        if checked:
            if self.viewerSection is None:
                self.viewerSection = PygdalsarViewerSection()
                # Pass the viewer instance to onClosePlugin
                self.viewerSection.closingPlugin.connect(
                    lambda: self.onClosePlugin(self.viewerSection)
                )
            self.iface.addDockWidget(Qt.BottomDockWidgetArea, self.viewerSection)
            self.viewerSection.show()
        else:
            if self.viewerSection is not None:
                self.viewerSection.close()

    def run_ts(self, checked: bool):
        if checked:
            if self.viewerTS is None:
                self.viewerTS = PygdalsarViewerTS()
                # Pass the viewer instance to onClosePlugin
                self.viewerTS.closingPlugin.connect(
                    lambda: self.onClosePlugin(self.viewerTS)
                )
            self.iface.addDockWidget(Qt.BottomDockWidgetArea, self.viewerTS)
            self.viewerTS.show()
        else:
            if self.viewerTS is not None:
                self.viewerTS.close()
