# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PygdalsarViewer
                                 A QGIS plugin
 Viewer tools for raster time series with multiple geometry aquisitions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Léo Letelier, Hugo Watine, Simon Daout
        email                : leo.letellier@univ-lorraine.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os.path

from qgis.PyQt.QtCore import QCoreApplication, QSettings, Qt, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
from .ui.about_dialog import AboutDialog
from .ui.pygdalsar_viewer_cube import PygdalsarViewerCube


class PygdalsarViewer:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "PygdalsarViewer_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&PyGdalSAR Viewer")
        self.toolbar = self.iface.addToolBar("PygdalsarViewer")
        self.toolbar.setObjectName("PygdalsarViewer")

        self.pluginIsActive = False
        self.viewerCube = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        return QCoreApplication.translate("PygdalsarViewer", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
        checkable=False,
    ):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        action.setCheckable(checkable)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI"""

        icon_path = ":/plugins/Pygdalsar_Viewer/icon.png"
        self.action_viewer = self.add_action(
            icon_path,
            text=self.tr("PyGdalSAR Viewer"),
            callback=self.run_cube,
            parent=self.iface.mainWindow(),
            checkable=True,
        )

        # TODO need an actual icon...
        icon_about = ":/plugins/Pygdalsar_Viewer/icon_about.png"
        self.add_action(
            icon_about,
            text=self.tr("About PyGdalSAR Viewer"),
            callback=self.run_about,
            parent=self.iface.mainWindow(),
            status_tip=self.tr("About this plugin"),
        )

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""
        self.viewerCube.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False
        self.action_viewer.setChecked(False)

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI"""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr("&PyGdalSAR Viewer"), action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar

    def run_cube(self, checked: bool):
        """Run the cube viewer"""
        if checked:
            if not self.pluginIsActive:
                self.pluginIsActive = True

                if self.viewerCube is None:
                    self.viewerCube = PygdalsarViewerCube()

                self.viewerCube.closingPlugin.connect(self.onClosePlugin)
                self.iface.addDockWidget(Qt.BottomDockWidgetArea, self.viewerCube)
                self.viewerCube.show()
        else:
            if self.viewerCube is not None:
                self.viewerCube.close()

    def run_about(self):
        """Open the About dialog"""
        dlg = AboutDialog(parent=self.iface.mainWindow())
        dlg.exec_()
